site_name:        GenieDeploy.jl
repo_url:         https://github.com/GenieFramework/GenieDeploy.jl
site_description: Deploying Genie apps to cloud
site_author:      Adrian Salceanu

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
